### ISSUE TITLE
Bad GIF quality due to Pillow

### ISSUE THREAD

**Issue by star-39** [laggykiller/rlottie-python#1]
Hi, thank you for this project, it solves the head-aching TGS converting problem.

However, the converted GIF has very strong color banding.

![image](https://user-images.githubusercontent.com/75669297/222080852-fe644a36-cba8-45cc-92c9-219b7bd06373.png)

It looks even uglier when it moves.

![AnimatedEmojies_🥳](https://user-images.githubusercontent.com/75669297/222176599-636994cf-66bc-4f83-a854-24c6c788ce3d.gif)

**Comment by laggykiller** [comment]
This issue is not quite related to this library...

However, I did found this issue: https://github.com/python-pillow/Pillow/issues/4941

Hope this helps!

**Comment by laggykiller** [comment]
I see, but if I want the library to produce high quality GIF with `Image.LIBIMAGEQUANT`, then I have to add `libimagequant` as dependency in this project, which I think is a feature creep. I think this job should be left to users, as there is many ways to quantize a image (e.g. number of colors, method), each with pros and cons (e.g. File size, image quality), and there is no single best method.

If users want to create gif with `Image.LIBIMAGEQUANT`, they can just easily (?):
```
from rlottie_python import LottieAnimation
from PIL import Image

anim = LottieAnimation.from_file('example/sample.json')
totalframe = anim.lottie_animation_get_totalframe()
frame_duration = 1000 / anim.lottie_animation_get_framerate()

im_list = []
for frame in totalframe:
    im = anim.render_pillow_frame(frame_num=frame).copy()
    im = im.quantize(255, method=Image.LIBIMAGEQUANT)
    im_list.append(im)

im_list[0].save('animation.gif', save_all=True, append_images=im_list[1:], duration=int(frame_duration))
```

**Comment by star-39** [comment]
Not exactly that you must use `Image.LIBIMAGEQUANT` to improve quality.... I just happen to found that it did.

Well, if you think current `save_animation` result is okay, then it's okay! Thank you.
