### ISSUE TITLE
Is the code support to parse assets in json file? 

### ISSUE THREAD

**Issue by yugaocheng** [laggykiller/rlottie-python#2]
i can get empty png files from my owner data when run rlottie-python/example/example.py 

but i got right result in sample.json. The different between them is that i use raster image in assets.

**Comment by laggykiller** [comment]
Let me clarify: If you replace sample.json with your own lottie file, you get an empty png as result? Your lottie file somehow contains raster assets?

I have never heard of lottie files that contain raster assets. Can you send me the file you were using?

**Comment by yugaocheng** [comment]
yeah, Maybe my expression is not particularly accurate，but the raster image can be inserted as reference image as the fields ‘u‘ and ’p‘ described. 
well,  how can i send u my own sample file?

**Comment by laggykiller** [comment]
I think you can upload it here by drag and drop. If that does not work, try to change the extension to txt, or upload to cloud drive and share

**Comment by yugaocheng** [comment]
[data.txt](https://github.com/laggykiller/rlottie-python/files/12121739/data.txt)

**Comment by laggykiller** [comment]
I see no problem

```
from rlottie_python import LottieAnimation

json_file = 'data.json'

with LottieAnimation.from_file(path=json_file) as anim:
    anim.save_animation('test1.apng')
    anim.save_animation('test2.gif')
    anim.save_animation('test3.webp')
```

Maybe it's because the circles are white, and the transparent background is displayed as white on your side, or you accidentally cause the transparent background to become white background?

**Comment by laggykiller** [comment]
Likely not a problem with this repo. I am closing this for now. If you still encounter difficulties, please re-open issue with more information.
