### ISSUE TITLE
Add wheels for the aarch64 architecture

### ISSUE THREAD

**Issue by Exploder98** [laggykiller/rlottie-python#3]
Would it be possible to provide aarch64 (64-bit ARM) wheels for this project? At least the underlying library, rlottie, claims to support this architecture.

**Comment by laggykiller** [comment]
Added aarch64, along with i686, ppc64le, s390x in v1.1.2

I don't have hardware to test. Please check if it works.

**Comment by Exploder98** [comment]
Thanks! I can confirm that on linux/aarch64 at least the example runs successfully and produces files that seem to be correct.

**Comment by laggykiller** [comment]
Thanks for testing!
