### ISSUE TITLE
Help in building  ARM 64-bit architecture (AARCH64) for rlottie.

### ISSUE THREAD

**Issue by salvecom333** [laggykiller/rlottie-python#4]
i got this error when i installed a test apk in my phone, OSError: dlopen failed: "/data/data/org.lottie.lottie/files/app/_python_bundle/site-packages/rlottie_python/librlottie.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183). How can i build a AARCH64 architecture to get this to work, or do you have a librlottie.so file that already has this architecture. I'm trying to build a simple lottie viewer to get this to work in the kivy framework, and it does work in my windows enviroment, but in andriod it doesn't work. Can you point me to right direction how i can accomplish this. anything in the c-language is beyond me. Any help is greatly apprecitated.

**Comment by laggykiller** [comment]
You have to somehow install the Linux aarch64 version of rlottie-python wheel instead of x86_64 version (https://pypi.org/project/rlottie-python/#files). Good luck.

**Comment by salvecom333** [comment]
Thank you so much for your help. God bless you man.

**Comment by laggykiller** [comment]
Try this:
```
python -m venv venv
venv/Scripts/activate # On Windows
source venv/bin/activate # On Linux
pip install rlottie-python --platform manylinux2014_aarch64 --only-binary=:all: -t venv/lib/python3.xx/site-packages # Replace 3.xx with your version of python
```
