### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yeldarby** [laggykiller/rlottie-python#5]
Hi, this package looks great. But I saw that it uses the GPL license and I think that will prevent me from being able to use it.

I’m hoping to use it to add support for Lottie files to an MIT-licensed package. I don’t think this is allowed under GPL. We’d have to change our license to GPL which means all our users would have to change their licenses as well.

Any chance you’ve considered a less viral license like LGPL which would require any changes to this library to be open source under LGPL but wouldn’t require _users_ of the library to be GPL? (Or alternatively MIT or Apache-2.0 licenses which are even less restrictive.)

**Comment by laggykiller** [comment]
Think I went a bit overkill with GPL license. Releasing with LGPL in v1.2.0. Pypi package is underway, please wait for github action to finish.
